"""Estados de materialización operativa de oficio → iniciador."""

from __future__ import annotations

MATERIALIZADO = "MATERIALIZADO"
PENDIENTE_DOMICILIO = "PENDIENTE_DOMICILIO"
PENDIENTE_MATERIALIZACION = "PENDIENTE_MATERIALIZACION"

TIPOS_INICIADOR_OFICIO_MATERIALIZACION = (
    "REINSPECCION_OFICIO",
    "VERIFICAR_INFORMAR_OFICIO",
    "RATIFICACION_CLAUSURA_OFICIO",
    "RATIFICACION_DECOMISO_OFICIO",
)
