import { StyleSheet } from "@react-pdf/renderer";

import {
  PDF_DESIGN_COLORS,
  PDF_DESIGN_FONT,
  pdfInformePage,
  pdfInformeSectionSeparator,
  pdfInformeTable,
  pdfInformeTypography,
  pdfTableCellBorder,
} from "../../../documentos/core/pdfDesignTokens";

export const dashboardPdfStyles = StyleSheet.create({
  page: {
    ...pdfInformePage,
    paddingTop: 28,
    paddingBottom: 32,
    paddingHorizontal: 32,
  },
  membreteImg: {
    width: "100%",
    height: 52,
    objectFit: "contain",
    marginBottom: 8,
  },
  mainTitle: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 15,
    fontWeight: 700,
    color: PDF_DESIGN_COLORS.titleBlue,
    textAlign: "center",
    textTransform: "uppercase",
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  periodLine: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 11,
    fontWeight: 700,
    color: PDF_DESIGN_COLORS.textPrimary,
    textAlign: "center",
    marginBottom: 4,
  },
  metaLine: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 8,
    fontWeight: 400,
    color: PDF_DESIGN_COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 2,
  },
  sectionTitle: {
    ...pdfInformeTypography.sectionTitle,
    ...pdfInformeSectionSeparator,
    marginTop: 10,
    textTransform: "uppercase",
  },
  subSectionTitle: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 9,
    fontWeight: 700,
    color: PDF_DESIGN_COLORS.sectionDarkBlue,
    marginTop: 6,
    marginBottom: 3,
  },
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 4,
  },
  kpiCard: {
    width: "48%",
    borderWidth: 0.5,
    borderColor: PDF_DESIGN_COLORS.tableRowBorder,
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: PDF_DESIGN_COLORS.grupoCardBg,
  },
  kpiLabel: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 7,
    fontWeight: 400,
    color: PDF_DESIGN_COLORS.textSecondary,
    marginBottom: 2,
  },
  kpiValue: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 10,
    fontWeight: 700,
    color: PDF_DESIGN_COLORS.textPrimary,
  },
  tableHeader: {
    ...pdfInformeTable.headerRow,
    marginTop: 2,
  },
  tableRow: {
    ...pdfTableCellBorder,
    flexDirection: "row",
    backgroundColor: PDF_DESIGN_COLORS.tableRowBg,
    paddingVertical: 3,
    paddingHorizontal: 4,
    alignItems: "center",
  },
  tableHeaderCell: {
    ...pdfInformeTypography.tableHeaderCell,
    flex: 1,
  },
  tableBodyCell: {
    ...pdfInformeTypography.tableBodyCell,
    flex: 1,
    fontSize: 7.5,
  },
  tableBodyCellRight: {
    ...pdfInformeTypography.tableBodyCell,
    flex: 0.35,
    fontSize: 7.5,
    textAlign: "right",
  },
  emptyLine: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 8,
    fontStyle: "italic",
    color: PDF_DESIGN_COLORS.textMuted,
    marginVertical: 4,
  },
  note: {
    fontFamily: PDF_DESIGN_FONT.ui,
    fontSize: 7,
    color: PDF_DESIGN_COLORS.textMuted,
    marginTop: 4,
    fontStyle: "italic",
  },
  twoColRow: {
    flexDirection: "row",
    gap: 8,
  },
  halfCol: {
    flex: 1,
  },
  footer: {
    position: "absolute",
    bottom: 14,
    left: 32,
    right: 32,
    ...pdfInformeTypography.caption,
    textAlign: "center",
    color: PDF_DESIGN_COLORS.textMuted,
  },
});
