import type { TrabajoDelDiaRow } from "../types/completarTrabajos.types";

/**
 * Respuesta mock estructurada como futuro GET /completar-trabajos?fecha=...
 * (sin llamada HTTP real).
 */
export function getMockTrabajosDelDiaRows(fecha: string): TrabajoDelDiaRow[] {
  return [
    {
      id: `mock-${fecha}-1`,
      fecha,
      tipoIniciador: "DENUNCIA",
      ordenTrabajo: "OT-240315",
      inspectores: "García, López",
      calle: "Av. Sarmiento",
      interseccion: "Mitre",
      nombre: "Juan",
      apellido: "Pérez",
      dni: "30123456",
      contraproducencia: null,
      actaInspeccion: null,
      notificacion: null,
      actaComprobacion: null,
      motivo: null,
      actaClausura: null,
      actaDecomiso: null,
      kilosDecomisados: null,
      motivo1: null,
      motivo2: null,
      motivo3: null,
    },
    {
      id: `mock-${fecha}-2`,
      fecha,
      tipoIniciador: "RELEVAMIENTO",
      ordenTrabajo: "OT-240316",
      inspectores: "Martínez",
      calle: "Laprida 450",
      interseccion: "-",
      nombre: "María",
      apellido: "Gómez",
      dni: "28987654",
      contraproducencia: null,
      actaInspeccion: null,
      notificacion: null,
      actaComprobacion: null,
      motivo: null,
      actaClausura: null,
      actaDecomiso: null,
      kilosDecomisados: null,
      motivo1: null,
      motivo2: null,
      motivo3: null,
    },
    {
      id: `mock-${fecha}-3`,
      fecha,
      tipoIniciador: "REINSPECCION_NOTIFICACION",
      ordenTrabajo: null,
      inspectores: "García",
      calle: "San Martín 1200",
      interseccion: "Congreso",
      nombre: "Carlos",
      apellido: "Ruiz",
      dni: "31234567",
      contraproducencia: null,
      actaInspeccion: null,
      notificacion: null,
      actaComprobacion: null,
      motivo: null,
      actaClausura: null,
      actaDecomiso: null,
      kilosDecomisados: null,
      motivo1: null,
      motivo2: null,
      motivo3: null,
    },
  ];
}
