/** Mapeo de errores (backend / grilla Glide → snake_case del formulario de actuación). */
export const ACTUACION_ROW_ERROR_KEY_MAP: Record<string, string> = {
  "Orden de trabajo": "orden_trabajo_numero",
  orden_trabajo_numero: "orden_trabajo_numero",
  orden_trabajo: "orden_trabajo_numero",
  "Fecha actuación": "fecha_actuacion",
  fecha_actuacion: "fecha_actuacion",
  fecha: "fecha_actuacion",
  "Tipo actuación": "tipo_actuacion",
  tipo_actuacion: "tipo_actuacion",
  tipo: "tipo_actuacion",
  Contraproducencia: "contraproducencia",
  contraproducencia: "contraproducencia",
  "Inspector 1": "inspector1",
  "Inspector 2": "inspector2",
  "Inspector 3": "inspector3",
  Inspectores: "inspectores",
  inspectores: "inspectores",
  inspector: "inspectores",
  Calle: "calle",
  calle: "calle",
  domicilio: "calle",
  Número: "numero",
  numero: "numero",
  "Tipo de numeración": "numero_tipo",
  numero_tipo: "numero_tipo",
  Rubro: "rubro_nombre",
  rubro_nombre: "rubro_nombre",
  rubro: "rubro_nombre",
  Apellido: "contrib_apellido",
  Nombre: "contrib_nombre",
  "Razón social": "razon_social",
  DNI: "doc_nro",
  "Acta inspección": "acta_inspeccion_num",
  acta_inspeccion_num: "acta_inspeccion_num",
  nro_acta_inspeccion: "acta_inspeccion_num",
  "Acta notificación": "acta_notificacion_num",
  acta_notificacion_num: "acta_notificacion_num",
  nro_acta_notificacion: "acta_notificacion_num",
  "Motivo notif 1": "notificacion_motivo_1",
  "Motivo notif 2": "notificacion_motivo_2",
  "Motivo notif 3": "notificacion_motivo_3",
  "Acta comprobación": "acta_comprobacion_num",
  acta_comprobacion_num: "acta_comprobacion_num",
  nro_acta_comprobacion: "acta_comprobacion_num",
  "Motivo comprobación": "comprobacion_motivo",
  comprobacion_motivo: "comprobacion_motivo",
  "Acta clausura": "acta_clausura_num",
  acta_clausura_num: "acta_clausura_num",
  nro_acta_clausura: "acta_clausura_num",
  "Acta decomiso": "acta_decomiso_num",
  acta_decomiso_num: "acta_decomiso_num",
  nro_acta_decomiso: "acta_decomiso_num",
  "Kilos decomiso": "decomiso_kilos_total",
  "Nombre local": "nombre_local",
  "Acta notificación previa": "notificacion_previa_num",
  "Acta comprobación previa": "comprobacion_previa_num",
  "Expediente año": "expediente_anio",
  "Expediente número": "expediente_numero",
  "Oficio año": "oficio_anio",
  "Oficio número": "oficio_numero",
  "Oficio causa": "oficio_causa",
  oficio_numero: "oficio_numero",
  numero_oficio: "oficio_numero",
  oficio_anio: "oficio_anio",
  oficio_causa: "oficio_causa",
  oficio: "oficio_numero",
  expediente_numero: "expediente_numero",
  expediente_anio: "expediente_anio",
  expediente: "expediente_numero",
};
