"""barrio y domicilio

Revision ID: 0637d9100a60
Revises: a108dbb61edd
Create Date: 2025-12-06 20:40:08.365281

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '0637d9100a60'
down_revision = 'a108dbb61edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distrito_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.create_index('idx_barrio_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_barrio_distrito_id'), ['distrito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barrio_nombre'), ['nombre'], unique=False)

    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=128), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('contribuyente_id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contribuyente_id'], ['contribuyente.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domicilio_barrio_id'), ['barrio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle'), ['calle'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_contribuyente_id'), ['contribuyente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_rubro_id'), ['rubro_id'], unique=False)

 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domicilio_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_numero'))
        batch_op.drop_index(batch_op.f('ix_domicilio_contribuyente_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle'))
        batch_op.drop_index(batch_op.f('ix_domicilio_barrio_id'))

    op.drop_table('domicilio')
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barrio_nombre'))
        batch_op.drop_index(batch_op.f('ix_barrio_distrito_id'))
        batch_op.drop_index('idx_barrio_geom', postgresql_using='gist')

    op.drop_table('barrio')
    # ### end Alembic commands ###
