"""actas

Revision ID: 11ae8ed6b144
Revises: 0637d9100a60
Create Date: 2025-12-06 21:45:29.296052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ae8ed6b144'
down_revision = '0637d9100a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_acomp_numero_anio')
    )
    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobacion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_motivo'), ['motivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_an_numero_anio')
    )
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ot_numero_anio')
    )
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_trabajo_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_trabajo_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_trabajo_numero_acta'), ['numero_acta'], unique=False)



  

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_mes'))
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_anio'))

    op.drop_table('orden_trabajo')
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_notificacion_mes'))
        batch_op.drop_index(batch_op.f('ix_notificacion_anio'))

    op.drop_table('notificacion')
    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobacion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_motivo'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_mes'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_anio'))

    op.drop_table('comprobacion')
    # ### end Alembic commands ###
