"""tabla n

Revision ID: 137383399ee5
Revises: 70bc93d94ef4
Create Date: 2025-12-07 03:34:56.476235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137383399ee5'
down_revision = '70bc93d94ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuaciones_inspector',
    sa.Column('actuaciones_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actuaciones_id'], ['actuaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actuaciones_id', 'inspector_id')
    )
   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_table('actuaciones_inspector')
    # ### end Alembic commands ###
