"""init sandbox

Revision ID: 138475164002
Revises: 
Create Date: 2025-12-31 12:01:15.107471

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '138475164002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_acomp_numero_anio')
    )
    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobacion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_motivo'), ['motivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('contribuyente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=128), nullable=True),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('documento', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribuyente_apellido'), ['apellido'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_nombre'), ['nombre'], unique=False)

    op.create_table('distrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.create_index('idx_distrito_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_distrito_nombre'), ['nombre'], unique=True)

    op.create_table('motivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motivo_nombre'), ['nombre'], unique=False)

    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_an_numero_anio')
    )
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ot_numero_anio')
    )
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_trabajo_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_trabajo_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_trabajo_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubro_nombre'), ['nombre'], unique=True)

    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('TARDE', 'MANIANA', name='tipo_turno', native_enum=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turno_turno'), ['turno'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_nombre'), ['nombre'], unique=False)

    op.create_table('barrio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distrito_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.create_index('idx_barrio_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_barrio_distrito_id'), ['distrito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barrio_nombre'), ['nombre'], unique=False)

    op.create_table('inspector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('legajo', sa.String(length=5), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspector_legajo'), ['legajo'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_turno_id'), ['turno_id'], unique=False)

    op.create_table('notificacion_motivo',
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motivo'], ['motivo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id', 'motivo')
    )
    op.create_table('oficio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oficio', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('causa', sa.String(length=10), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_oficio', 'anio', name='uq_of_numero_anio')
    )
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oficio_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_causa'), ['causa'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_numero_oficio'), ['numero_oficio'], unique=False)

    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=128), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cp', sa.String(length=4), nullable=True),
    sa.Column('ciudad', sa.String(length=110), nullable=True),
    sa.Column('provincia', sa.String(length=8), nullable=True),
    sa.Column('pais', sa.String(length=25), nullable=True),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('contribuyente_id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contribuyente_id'], ['contribuyente.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domicilio_barrio_id'), ['barrio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle'), ['calle'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_contribuyente_id'), ['contribuyente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_rubro_id'), ['rubro_id'], unique=False)

    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_expediente', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.String(length=4), nullable=False),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('oficio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_expediente', 'anio', name='uq_ex_numero_anio')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expediente_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_numero_expediente'), ['numero_expediente'], unique=False)

    op.create_table('actuaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INSPECCION', 'REINSPECCION', 'RATIFICACION_CLAUSURA', 'RATIFICACION_DECOMISO', 'VERIFICAR_E_IFORMAR', 'TRANSPORTE', name='tipo_actuacion', native_enum=False), nullable=True),
    sa.Column('contraproducencia', sa.Enum('LOCAL_CERRADO', 'NO_EXISTE', 'INCLEMENCIA_TIEMPO', 'ZONA_ROJA', 'NO_HUBO', 'OTROS', name='contraproducencia', native_enum=False), nullable=True),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=False),
    sa.Column('notificacion_id', sa.Integer(), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['orden_trabajo.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.create_index('idx_tipo_mes_anio', ['tipo', 'mes', 'anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_contraproducencia'), ['contraproducencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_notificacion_id'), ['notificacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_orden_trabajo_id'), ['orden_trabajo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_actuaciones_tipo'), ['tipo'], unique=False)

    op.create_table('relevamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relevamiento_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_rubro_id'), ['rubro_id'], unique=False)

    op.create_table('actuaciones_inspector',
    sa.Column('actuaciones_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actuaciones_id'], ['actuaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actuaciones_id', 'inspector_id')
    )
    op.create_table('clausura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ac_numero_anio')
    )
    with op.batch_alter_table('clausura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clausura_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_clausura_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_clausura_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_clausura_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('decomiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ad_numero_anio')
    )
    with op.batch_alter_table('decomiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decomiso_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_decomiso_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_decomiso_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_decomiso_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('inspeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ai_numero_anio')
    )
    with op.batch_alter_table('inspeccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspeccion_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspeccion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspeccion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspeccion_numero_acta'), ['numero_acta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspeccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspeccion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_mes'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_anio'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_actuacion_id'))

    op.drop_table('inspeccion')
    with op.batch_alter_table('decomiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decomiso_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_decomiso_mes'))
        batch_op.drop_index(batch_op.f('ix_decomiso_anio'))
        batch_op.drop_index(batch_op.f('ix_decomiso_actuacion_id'))

    op.drop_table('decomiso')
    with op.batch_alter_table('clausura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clausura_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_clausura_mes'))
        batch_op.drop_index(batch_op.f('ix_clausura_anio'))
        batch_op.drop_index(batch_op.f('ix_clausura_actuacion_id'))

    op.drop_table('clausura')
    op.drop_table('actuaciones_inspector')
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relevamiento_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_mes'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_anio'))

    op.drop_table('relevamiento')
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actuaciones_tipo'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_orden_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_notificacion_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_mes'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_contraproducencia'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_anio'))
        batch_op.drop_index('idx_tipo_mes_anio')

    op.drop_table('actuaciones')
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_numero_expediente'))
        batch_op.drop_index(batch_op.f('ix_expediente_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_expediente_anio'))

    op.drop_table('expediente')
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domicilio_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_numero'))
        batch_op.drop_index(batch_op.f('ix_domicilio_contribuyente_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle'))
        batch_op.drop_index(batch_op.f('ix_domicilio_barrio_id'))

    op.drop_table('domicilio')
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oficio_numero_oficio'))
        batch_op.drop_index(batch_op.f('ix_oficio_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_oficio_causa'))
        batch_op.drop_index(batch_op.f('ix_oficio_anio'))

    op.drop_table('oficio')
    op.drop_table('notificacion_motivo')
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspector_turno_id'))
        batch_op.drop_index(batch_op.f('ix_inspector_nombre'))
        batch_op.drop_index(batch_op.f('ix_inspector_legajo'))

    op.drop_table('inspector')
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barrio_nombre'))
        batch_op.drop_index(batch_op.f('ix_barrio_distrito_id'))
        batch_op.drop_index('idx_barrio_geom', postgresql_using='gist')

    op.drop_table('barrio')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nombre'))

    op.drop_table('usuario')
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turno_turno'))

    op.drop_table('turno')
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubro_nombre'))

    op.drop_table('rubro')
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_mes'))
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_anio'))

    op.drop_table('orden_trabajo')
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_notificacion_mes'))
        batch_op.drop_index(batch_op.f('ix_notificacion_anio'))

    op.drop_table('notificacion')
    with op.batch_alter_table('motivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motivo_nombre'))

    op.drop_table('motivo')
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distrito_nombre'))
        batch_op.drop_index('idx_distrito_geom', postgresql_using='gist')

    op.drop_table('distrito')
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribuyente_nombre'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_documento'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_apellido'))

    op.drop_table('contribuyente')
    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobacion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_motivo'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_mes'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_anio'))

    op.drop_table('comprobacion')
    # ### end Alembic commands ###
