"""actas,solas

Revision ID: 4ad3a8f8b165
Revises: d137fb32046b
Create Date: 2025-12-07 03:26:12.665353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad3a8f8b165'
down_revision = 'd137fb32046b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clausura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ac_numero_anio')
    )
    with op.batch_alter_table('clausura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clausura_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_clausura_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_clausura_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_clausura_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('decomiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ad_numero_anio')
    )
    with op.batch_alter_table('decomiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decomiso_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_decomiso_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_decomiso_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_decomiso_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('inspeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ai_numero_anio')
    )
    with op.batch_alter_table('inspeccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspeccion_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspeccion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspeccion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspeccion_numero_acta'), ['numero_acta'], unique=False)

    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.create_index('idx_tipo_mes_anio', ['tipo', 'mes', 'anio'], unique=False)



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_tipo_mes_anio')

    with op.batch_alter_table('inspeccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspeccion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_mes'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_anio'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_actuacion_id'))

    op.drop_table('inspeccion')
    with op.batch_alter_table('decomiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decomiso_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_decomiso_mes'))
        batch_op.drop_index(batch_op.f('ix_decomiso_anio'))
        batch_op.drop_index(batch_op.f('ix_decomiso_actuacion_id'))

    op.drop_table('decomiso')
    with op.batch_alter_table('clausura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clausura_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_clausura_mes'))
        batch_op.drop_index(batch_op.f('ix_clausura_anio'))
        batch_op.drop_index(batch_op.f('ix_clausura_actuacion_id'))

    op.drop_table('clausura')
    # ### end Alembic commands ###
