"""oficio y expediente

Revision ID: 4e6bd4f6aa54
Revises: 11ae8ed6b144
Create Date: 2025-12-06 21:56:58.005343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6bd4f6aa54'
down_revision = '11ae8ed6b144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oficio', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('causa', sa.String(length=10), nullable=False),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_oficio', 'anio', name='uq_of_numero_anio')
    )
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oficio_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_causa'), ['causa'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_numero_oficio'), ['numero_oficio'], unique=False)

    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_expediente', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.String(length=4), nullable=False),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('oficio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_expediente', 'anio', name='uq_ex_numero_anio')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expediente_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_numero_expediente'), ['numero_expediente'], unique=False)



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_numero_expediente'))
        batch_op.drop_index(batch_op.f('ix_expediente_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_expediente_anio'))

    op.drop_table('expediente')
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oficio_numero_oficio'))
        batch_op.drop_index(batch_op.f('ix_oficio_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_oficio_causa'))
        batch_op.drop_index(batch_op.f('ix_oficio_anio'))

    op.drop_table('oficio')
    # ### end Alembic commands ###
