"""relevamiento

Revision ID: 5dccd89705fe
Revises: 137383399ee5
Create Date: 2025-12-07 03:36:38.621832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dccd89705fe'
down_revision = '137383399ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relevamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relevamiento_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_rubro_id'), ['rubro_id'], unique=False)

   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   

    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relevamiento_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_mes'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_anio'))

    op.drop_table('relevamiento')
    # ### end Alembic commands ###
