"""inspector

Revision ID: 70bc93d94ef4
Revises: 4ad3a8f8b165
Create Date: 2025-12-07 03:27:33.234117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bc93d94ef4'
down_revision = '4ad3a8f8b165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('legajo', sa.String(length=5), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspector_legajo'), ['legajo'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_turno_id'), ['turno_id'], unique=False)

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspector_turno_id'))
        batch_op.drop_index(batch_op.f('ix_inspector_nombre'))
        batch_op.drop_index(batch_op.f('ix_inspector_legajo'))

    op.drop_table('inspector')
    # ### end Alembic commands ###
