"""tablas catalogo

Revision ID: a108dbb61edd
Revises: 65b03fa1165c
Create Date: 2025-12-06 19:56:10.752752

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2
# revision identifiers, used by Alembic.
revision = 'a108dbb61edd'
down_revision = '65b03fa1165c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribuyente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('documento', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribuyente_apellido'), ['apellido'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_nombre'), ['nombre'], unique=False)

    op.create_table('distrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distrito_nombre'), ['nombre'], unique=True)

    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubro_nombre'), ['nombre'], unique=True)

    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('TARDE', 'MANIANA', name='tipo_turno', native_enum=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turno_turno'), ['turno'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nombre'))

    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turno_turno'))

    op.drop_table('turno')
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubro_nombre'))

    op.drop_table('rubro')
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distrito_nombre'))

    op.drop_table('distrito')
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribuyente_nombre'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_documento'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_apellido'))

    op.drop_table('contribuyente')
    # ### end Alembic commands ###
