"""actuaciones

Revision ID: d137fb32046b
Revises: 4e6bd4f6aa54
Create Date: 2025-12-06 22:03:38.293506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd137fb32046b'
down_revision = '4e6bd4f6aa54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INSPECCION', 'REINSPECCION', 'RATIFICACION_CLAUSURA', 'RATIFICACION_DECOMISO', 'VERIFICAR_E_IFORMAR', name='tipo', native_enum=False), nullable=False),
    sa.Column('contraproducencia', sa.Enum('LOCAL_CERRADO', 'NO_EXISTE', 'INCLEMENCIA_TIEMPO', 'ZONA_ROJA', 'NO_HUBO', 'OTROS', name='contra_enum', native_enum=False), nullable=True),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=False),
    sa.Column('notificacion_id', sa.Integer(), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['orden_trabajo.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actuaciones_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_contraproducencia'), ['contraproducencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_notificacion_id'), ['notificacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_orden_trabajo_id'), ['orden_trabajo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_actuaciones_tipo'), ['tipo'], unique=False)

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actuaciones_tipo'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_orden_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_notificacion_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_mes'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_contraproducencia'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_anio'))

    op.drop_table('actuaciones')
    # ### end Alembic commands ###
