from .actuaciones_inspector import actuaciones_inspector
from .usuario import Usuario
from .turno import Turno
from .rubro import Rubro
from .contribuyente import Contribuyente
from .distrito import Distrito
from .barrio import Barrio
from .domicilio import Domicilio
from .notificacion import Notificacion
from .orden_de_trabajo import OrdenTrabajo
from .comprobacion import Comprobacion
from .oficio import Oficio
from .expediente import Expediente
from .actuaciones import Actuaciones
from .inspeccion import Inspeccion
from .clausura import Clausura
from .decomiso import Decomiso
from .inspector import Inspector
from .relevamiento import Relevamiento