from .actuaciones import Actuaciones
from .actuaciones_inspector import actuaciones_inspector
from .barrio import Barrio
from .clausura import Clausura
from .comprobacion import Comprobacion
from .contribuyente import Contribuyente
from .decomiso import Decomiso
from .distrito import Distrito
from .domicilio import Domicilio
from .expediente import Expediente
from .inspeccion import Inspeccion
from .inspector import Inspector
from .notificacion import Notificacion
from .oficio import Oficio
from .orden_de_trabajo import OrdenTrabajo
from .relevamiento import Relevamiento
from .rubro import Rubro
from .turno import Turno
from .usuario import Usuario
