"""calle catalogo canon_base

Revision ID: 278c6ce2e633
Revises: 9841d79dfa00
Create Date: 2026-02-01 05:14:33.017671

"""
from alembic import op
import sqlalchemy as sa
import unicodedata
import re


# revision identifiers, used by Alembic.
revision = '278c6ce2e633'
down_revision = '9841d79dfa00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calle_catalogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canon_base', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_calle_catalogo_canon_base'), ['canon_base'], unique=False)
    _backfill_canon_base()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calle_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calle_catalogo_canon_base'))
        batch_op.drop_column('canon_base')

    # ### end Alembic commands ###


_SPACE_RE = re.compile(r"\s+")
_PUNCT_RE = re.compile(r"[.,;:\-_/]")
_VIA_TYPES = {
    "calle",
    "avenida",
    "pasaje",
    "camino",
    "ruta",
    "boulevard",
    "diagonal",
    "autopista",
    "travesia",
    "travesía",
}
_ABBREV_MAP = {
    "av": "avenida",
    "avda": "avenida",
    "avd": "avenida",
    "pje": "pasaje",
    "pje.": "pasaje",
    "pza": "plaza",
    "diag": "diagonal",
}


def _normalize_street(text: str) -> str:
    s = (text or "").strip().lower()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = _PUNCT_RE.sub(" ", s)
    s = _SPACE_RE.sub(" ", s).strip()
    if not s:
        return ""
    tokens = s.split(" ")
    tokens = [_ABBREV_MAP.get(t, t) for t in tokens]
    return " ".join(tokens)


def _street_base(text: str) -> str:
    s = _normalize_street(text)
    if not s:
        return ""
    tokens = s.split(" ")
    if tokens and tokens[0] in _VIA_TYPES:
        tokens = tokens[1:]
    return " ".join(tokens).strip()


def _backfill_canon_base() -> None:
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, nombre_canonico FROM calle_catalogo")).fetchall()
    for rid, canon in rows:
        base = _street_base(canon)
        conn.execute(
            sa.text("UPDATE calle_catalogo SET canon_base = :base WHERE id = :id"),
            {"base": base, "id": rid},
        )
