"""auto migration

Revision ID: 450014dac037
Revises: a00ee416407f
Create Date: 2026-03-19 00:21:03.929487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450014dac037'
down_revision = 'a00ee416407f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=True)

    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)

    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)

    # ### end Alembic commands ###
