"""arreglo

Revision ID: 474ea4bf7edf
Revises: 6538a9c6383f
Create Date: 2026-01-25 05:16:41.509108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '474ea4bf7edf'
down_revision = '6538a9c6383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('INSPECCION', 'REINSPECCION', 'RATIFICACION DE CLAUSURA', 'RATIFICACION DE DECOMISO', 'VERIFICAR E INFORMAR', 'TRANSPORTE', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('contraproducencia',
               existing_type=mysql.ENUM('LOCAL CERRADO', 'NO EXISTE/NO ES EL RUBRO', 'CLIMA', 'ZONA ROJA', 'NO_HUBO', 'OTROS', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)

 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   

    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.alter_column('contraproducencia',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('LOCAL CERRADO', 'NO EXISTE/NO ES EL RUBRO', 'CLIMA', 'ZONA ROJA', 'NO_HUBO', 'OTROS', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('INSPECCION', 'REINSPECCION', 'RATIFICACION DE CLAUSURA', 'RATIFICACION DE DECOMISO', 'VERIFICAR E INFORMAR', 'TRANSPORTE', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
