"""domicilio geocode table

Revision ID: 6f1d2c3b4a5e
Revises: 278c6ce2e633
Create Date: 2026-02-04 08:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f1d2c3b4a5e"
down_revision = "278c6ce2e633"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domicilio_geocode",
        sa.Column("domicilio_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Numeric(10, 7), nullable=True),
        sa.Column("lng", sa.Numeric(10, 7), nullable=True),
        sa.Column(
            "geo_status",
            sa.Enum(
                "PENDING",
                "OK",
                "REVIEW",
                "NO_MATCH",
                "ERROR",
                name="domicilio_geocode_status",
            ),
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("quality", sa.String(length=30), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("error_msg", sa.String(length=255), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
            server_onupdate=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.ForeignKeyConstraint(
            ["domicilio_id"],
            ["domicilio.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("domicilio_id"),
    )
    op.create_index("idx_geo_status", "domicilio_geocode", ["geo_status"], unique=False)
    op.create_index("idx_checked_at", "domicilio_geocode", ["checked_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_checked_at", table_name="domicilio_geocode")
    op.drop_index("idx_geo_status", table_name="domicilio_geocode")
    op.drop_table("domicilio_geocode")
    # ### end Alembic commands ###
