"""queonda

Revision ID: 882ad9b97369
Revises: 
Create Date: 2026-04-16 11:30:59.026107

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '882ad9b97369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calle_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_canonico', sa.String(length=255), nullable=False),
    sa.Column('canon_base', sa.String(length=255), nullable=True),
    sa.Column('nombre_key', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_canonico')
    )
    with op.batch_alter_table('calle_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calle_catalogo_canon_base'), ['canon_base'], unique=False)
        batch_op.create_index(batch_op.f('ix_calle_catalogo_nombre_key'), ['nombre_key'], unique=True)

    op.create_table('catalog_contraproducencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_contraproducencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_contraproducencia_nombre'), ['nombre'], unique=True)

    op.create_table('catalog_motivo_comprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_motivo_comprobacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_motivo_comprobacion_nombre'), ['nombre'], unique=True)

    op.create_table('catalog_tipo_actuacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_tipo_actuacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_tipo_actuacion_nombre'), ['nombre'], unique=True)

    op.create_table('comprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_acomp_numero_anio')
    )
    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobacion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_motivo'), ['motivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobacion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('contribuyente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=128), nullable=True),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('documento', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribuyente_apellido'), ['apellido'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribuyente_razon_social'), ['razon_social'], unique=False)

    op.create_table('distrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.create_index('idx_distrito_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_distrito_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_distrito_nombre'), ['nombre'], unique=True)

    op.create_table('establecimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('establecimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_establecimientos_nombre'), ['nombre'], unique=True)

    op.create_table('juzgado_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('juzgado_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_juzgado_catalogo_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_juzgado_catalogo_nombre'), ['nombre'], unique=True)

    op.create_table('lugares_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lugares_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lugares_trabajo_nombre'), ['nombre'], unique=False)

    op.create_table('motivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motivo_nombre'), ['nombre'], unique=False)

    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('plazo_dias', sa.Integer(), server_default='5', nullable=False),
    sa.Column('prorroga_dias', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_notificacion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_an_numero_anio')
    )
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_fecha_notificacion'), ['fecha_notificacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ot_numero_anio')
    )
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_trabajo_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_trabajo_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_orden_trabajo_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubro_nombre'), ['nombre'], unique=True)

    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('TARDE', 'MANIANA', name='tipo_turno', native_enum=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turno_turno'), ['turno'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'usuario', name='user_role_enum'), server_default='usuario', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('barrio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distrito_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.create_index('idx_barrio_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_barrio_distrito_id'), ['distrito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barrio_nombre'), ['nombre'], unique=False)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_establecimiento_id'), ['establecimiento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_fecha'), ['fecha'], unique=False)

    op.create_table('inspector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('legajo', sa.String(length=5), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspector_legajo'), ['legajo'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspector_turno_id'), ['turno_id'], unique=False)

    op.create_table('notificacion_motivo',
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motivo'], ['motivo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id', 'motivo')
    )
    op.create_table('oficio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oficio', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_oficio', sa.Date(), nullable=True),
    sa.Column('causa', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('juzgado_id', sa.Integer(), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['juzgado_id'], ['juzgado_catalogo.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('causa', 'anio', name='uq_of_causa_anio'),
    sa.UniqueConstraint('numero_oficio', 'anio', name='uq_of_numero_anio')
    )
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oficio_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_causa'), ['causa'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_fecha_oficio'), ['fecha_oficio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_juzgado_id'), ['juzgado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oficio_numero_oficio'), ['numero_oficio'], unique=False)

    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('apellido', sa.String(length=128), nullable=False),
    sa.Column('lugar_trabajo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lugar_trabajo_id'], ['lugares_trabajo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participantes_dni'), ['dni'], unique=True)
        batch_op.create_index(batch_op.f('ix_participantes_lugar_trabajo_id'), ['lugar_trabajo_id'], unique=False)

    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_codes_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_codes_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('avatar_key', sa.String(length=50), server_default='avatar1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('ruta_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno', sa.Enum('MANIANA', 'TARDE', name='tipo_turno'), nullable=False),
    sa.Column('estado_ruta', sa.Enum('BORRADOR', 'PUBLICADA', 'EN_CURSO', 'CERRADA', 'CANCELADA', name='estado_ruta_enum'), server_default='BORRADOR', nullable=False),
    sa.Column('numero', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'turno', 'numero', name='uq_ruta_trabajo_fecha_turno_numero')
    )
    with op.batch_alter_table('ruta_trabajo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruta_trabajo_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_trabajo_estado_ruta'), ['estado_ruta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_trabajo_fecha'), ['fecha'], unique=False)
        batch_op.create_index('ix_ruta_trabajo_fecha_turno_estado', ['fecha', 'turno', 'estado_ruta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_trabajo_turno'), ['turno'], unique=False)

    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=128), nullable=False),
    sa.Column('numero', sa.String(length=200), nullable=False),
    sa.Column('numero_tipo', sa.String(length=16), nullable=True),
    sa.Column('cp', sa.String(length=4), nullable=True),
    sa.Column('ciudad', sa.String(length=110), nullable=True),
    sa.Column('provincia', sa.String(length=8), nullable=True),
    sa.Column('pais', sa.String(length=25), nullable=True),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('distrito_id', sa.Integer(), nullable=True),
    sa.Column('contribuyente_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('calle_raw', sa.String(length=128), nullable=True),
    sa.Column('calle_normalizada', sa.String(length=128), nullable=True),
    sa.Column('calle_key', sa.String(length=128), nullable=True),
    sa.Column('calle_catalogo_id', sa.Integer(), nullable=True),
    sa.Column('calle_norm_status', sa.String(length=32), nullable=False),
    sa.Column('calle_norm_score', sa.Float(), nullable=True),
    sa.Column('calle_norm_error', sa.String(length=255), nullable=True),
    sa.Column('calle_norm_updated_at', sa.DateTime(), nullable=True),
    sa.Column('esquina_raw', sa.String(length=255), nullable=True),
    sa.Column('esquina_catalogo_id', sa.Integer(), nullable=True),
    sa.Column('esquina_normalizada', sa.String(length=255), nullable=True),
    sa.Column('esquina_norm_status', sa.String(length=16), nullable=True),
    sa.Column('esquina_norm_score', sa.Float(), nullable=True),
    sa.Column('esquina_norm_error', sa.String(length=255), nullable=True),
    sa.Column('esquina_norm_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['calle_catalogo_id'], ['calle_catalogo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contribuyente_id'], ['contribuyente.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['esquina_catalogo_id'], ['calle_catalogo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domicilio_barrio_id'), ['barrio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle'), ['calle'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle_catalogo_id'), ['calle_catalogo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle_key'), ['calle_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle_norm_status'), ['calle_norm_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_contribuyente_id'), ['contribuyente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_distrito_id'), ['distrito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_esquina_catalogo_id'), ['esquina_catalogo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_esquina_norm_status'), ['esquina_norm_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_numero_tipo'), ['numero_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_rubro_id'), ['rubro_id'], unique=False)

    op.create_table('evento_participante',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('NO_RINDIO', 'APROBADO', 'DESAPROBADO', 'INSCRIPTO', 'ASISTIO', 'AUSENTE', 'RINDIO', name='estado_evento_participante'), server_default='NO_RINDIO', nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id', 'participante_id')
    )
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_expediente', sa.String(length=6), nullable=False),
    sa.Column('fecha_expediente', sa.Date(), nullable=True),
    sa.Column('anio', sa.String(length=4), nullable=False),
    sa.Column('tipo_expediente', sa.Enum('ENVIO_ACTA', 'RESPUESTA_OFICIO', 'PRORROGA_NOTIFICACION', 'OTRO', name='tipo_expediente_enum'), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('notificacion_id', sa.Integer(), nullable=True),
    sa.Column('oficio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_expediente', 'anio', name='uq_ex_numero_anio')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expediente_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_fecha_expediente'), ['fecha_expediente'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_notificacion_id'), ['notificacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_numero_expediente'), ['numero_expediente'], unique=False)
        batch_op.create_index(batch_op.f('ix_expediente_tipo_expediente'), ['tipo_expediente'], unique=False)

    op.create_table('ruta_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_trabajo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruta_trabajo_id'], ['ruta_trabajo.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruta_trabajo_id', 'nombre', name='uq_ruta_grupo_ruta_nombre')
    )
    with op.batch_alter_table('ruta_grupo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruta_grupo_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_grupo_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_grupo_ruta_trabajo_id'), ['ruta_trabajo_id'], unique=False)

    op.create_table('denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTA', 'CERRADA', 'DESCARTADA', name='denuncia_estado_enum'), server_default='ABIERTA', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_denuncia_anio'), ['anio'], unique=False)
        batch_op.create_index('ix_denuncia_anio_mes_domicilio_id', ['anio', 'mes', 'domicilio_id'], unique=False)
        batch_op.create_index('ix_denuncia_anio_mes_estado', ['anio', 'mes', 'estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_denuncia_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_denuncia_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_denuncia_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_denuncia_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_denuncia_mes'), ['mes'], unique=False)

    op.create_table('domicilio_geocode',
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_status', sa.Enum('PENDING', 'OK', 'REVIEW', 'NO_MATCH', 'ERROR', 'NORM_PENDING', 'GEO_PENDING', name='domicilio_geocode_status'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('quality', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('error_msg', sa.String(length=255), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('addr_hash', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', 'REVERSE', name='domicilio_geocode_source'), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domicilio_id')
    )
    with op.batch_alter_table('domicilio_geocode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domicilio_geocode_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_geocode_geo_status'), ['geo_status'], unique=False)

    op.create_table('establecimiento_operativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('establecimiento_operativo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_establecimiento_operativo_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_establecimiento_operativo_domicilio_id'), ['domicilio_id'], unique=True)

    op.create_table('relevamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('turno_carga', sa.Enum('MANIANA', 'TARDE', name='tipo_turno'), nullable=True),
    sa.Column('esta_abierto', sa.Boolean(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relevamiento_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_esta_abierto'), ['esta_abierto'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_rubro_id'), ['rubro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_turno_carga'), ['turno_carga'], unique=False)

    op.create_table('ruta_grupo_inspector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_grupo_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruta_grupo_id'], ['ruta_grupo.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruta_grupo_id', 'inspector_id', name='uq_ruta_grupo_inspector')
    )
    with op.batch_alter_table('ruta_grupo_inspector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruta_grupo_inspector_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_grupo_inspector_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_grupo_inspector_ruta_grupo_id'), ['ruta_grupo_id'], unique=False)

    op.create_table('actuaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('contraproducencia', sa.String(length=255), nullable=True),
    sa.Column('nombre_local', sa.String(length=255), nullable=True),
    sa.Column('ec5_uuid', sa.String(length=36), nullable=True),
    sa.Column('resultado_cumplimiento_oficio', sa.Enum('CUMPLE', 'NO_CUMPLE', name='resultado_cumplimiento_oficio_enum'), nullable=True),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=False),
    sa.Column('notificacion_id', sa.Integer(), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('establecimiento_operativo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['establecimiento_operativo_id'], ['establecimiento_operativo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['orden_trabajo.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'tipo', 'comprobacion_id', name='uq_act_anio_tipo_comprobacion'),
    sa.UniqueConstraint('anio', 'tipo', 'notificacion_id', name='uq_act_anio_tipo_notificacion')
    )
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.create_index('idx_tipo_mes_anio', ['tipo', 'mes', 'anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_contraproducencia'), ['contraproducencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_ec5_uuid'), ['ec5_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_actuaciones_establecimiento_operativo_id'), ['establecimiento_operativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_nombre_local'), ['nombre_local'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_notificacion_id'), ['notificacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actuaciones_orden_trabajo_id'), ['orden_trabajo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_actuaciones_tipo'), ['tipo'], unique=False)

    op.create_table('actuacion_epicollect_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('entry_uuid', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='EPICOLLECT', nullable=False),
    sa.Column('payload_non_media', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actuacion_epicollect_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actuacion_epicollect_detalle_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_actuacion_epicollect_detalle_entry_uuid'), ['entry_uuid'], unique=False)

    op.create_table('actuacion_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actuacion_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actuacion_media_actuacion_id'), ['actuacion_id'], unique=False)

    op.create_table('actuaciones_inspector',
    sa.Column('actuaciones_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actuaciones_id'], ['actuaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actuaciones_id', 'inspector_id')
    )
    op.create_table('clausura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ac_numero_anio')
    )
    with op.batch_alter_table('clausura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clausura_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_clausura_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_clausura_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_clausura_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('decomiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ad_numero_anio')
    )
    with op.batch_alter_table('decomiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decomiso_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_decomiso_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_decomiso_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_decomiso_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('iniciador_ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_iniciador', sa.Enum('RELEVAMIENTO', 'DENUNCIA', 'REINSPECCION_OFICIO', 'REINSPECCION_NOTIFICACION', 'VERIFICAR_INFORMAR_OFICIO', 'RATIFICACION_CLAUSURA_OFICIO', 'RATIFICACION_DECOMISO_OFICIO', name='tipo_iniciador_enum'), nullable=False),
    sa.Column('estado_iniciador', sa.Enum('PENDIENTE', 'PLANIFICADO', 'EN_EJECUCION', 'CUMPLIDO', 'NO_REALIZADO_REPROGRAMAR', 'CERRADO', 'CERRADO_NO_EXISTE_LOCAL', 'ANULADO', name='estado_iniciador_enum'), server_default='PENDIENTE', nullable=False),
    sa.Column('fecha_origen', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.Column('turno_sugerido', sa.Enum('MANIANA', 'TARDE', name='tipo_turno'), nullable=True),
    sa.Column('prioridad', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cerrado_at', sa.DateTime(), nullable=True),
    sa.Column('cerrado_motivo', sa.String(length=255), nullable=True),
    sa.Column('denuncia_id', sa.Integer(), nullable=True),
    sa.Column('relevamiento_id', sa.Integer(), nullable=True),
    sa.Column('notificacion_id', sa.Integer(), nullable=True),
    sa.Column('comprobacion_id', sa.Integer(), nullable=True),
    sa.Column('oficio_id', sa.Integer(), nullable=True),
    sa.Column('actuacion_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comprobacion_id'], ['comprobacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncia.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacion.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficio.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['relevamiento_id'], ['relevamiento.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iniciador_ruta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_actuacion_id'), ['actuacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_anio'), ['anio'], unique=False)
        batch_op.create_index('ix_iniciador_ruta_anio_mes_estado', ['anio', 'mes', 'estado_iniciador'], unique=False)
        batch_op.create_index('ix_iniciador_ruta_anio_mes_tipo', ['anio', 'mes', 'tipo_iniciador'], unique=False)
        batch_op.create_index('ix_iniciador_ruta_anio_mes_turno_estado', ['anio', 'mes', 'turno_sugerido', 'estado_iniciador'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_comprobacion_id'), ['comprobacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_denuncia_id'), ['denuncia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_domicilio_id'), ['domicilio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_estado_iniciador'), ['estado_iniciador'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_fecha_origen'), ['fecha_origen'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_notificacion_id'), ['notificacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_oficio_id'), ['oficio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_relevamiento_id'), ['relevamiento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_tipo_iniciador'), ['tipo_iniciador'], unique=False)
        batch_op.create_index(batch_op.f('ix_iniciador_ruta_turno_sugerido'), ['turno_sugerido'], unique=False)

    op.create_table('inspeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_acta', sa.String(length=6), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acta', 'anio', name='uq_ai_numero_anio')
    )
    with op.batch_alter_table('inspeccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspeccion_actuacion_id'), ['actuacion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspeccion_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspeccion_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspeccion_numero_acta'), ['numero_acta'], unique=False)

    op.create_table('ruta_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_trabajo_id', sa.Integer(), nullable=False),
    sa.Column('ruta_grupo_id', sa.Integer(), nullable=True),
    sa.Column('iniciador_ruta_id', sa.Integer(), nullable=False),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('estado_ruta_item', sa.Enum('PENDIENTE_ASIGNACION', 'ASIGNADO', 'EN_PROCESO', 'FINALIZADO', 'NO_REALIZADO', 'CANCELADO', name='estado_ruta_item_enum'), server_default='PENDIENTE_ASIGNACION', nullable=False),
    sa.Column('estado_ejecucion', sa.Enum('REALIZADO', 'NO_REALIZADO', name='estado_ejecucion_enum'), nullable=True),
    sa.Column('motivo_no_realizado', sa.Enum('LOCAL_CERRADO', 'INCLEMENCIA_TIEMPO', 'NO_EXISTE_LOCAL', 'OTRO', name='motivo_no_realizado_enum'), nullable=True),
    sa.Column('observaciones_ejecucion', sa.Text(), nullable=True),
    sa.Column('actuacion_id', sa.Integer(), nullable=True),
    sa.Column('ejecutado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('ejecutado_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ejecutado_por_user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['iniciador_ruta_id'], ['iniciador_ruta.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['orden_trabajo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ruta_grupo_id'], ['ruta_grupo.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ruta_trabajo_id'], ['ruta_trabajo.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruta_trabajo_id', 'iniciador_ruta_id', name='uq_ruta_item_ruta_iniciador')
    )
    with op.batch_alter_table('ruta_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruta_item_actuacion_id'), ['actuacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_ejecutado_por_user_id'), ['ejecutado_por_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_estado_ejecucion'), ['estado_ejecucion'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_estado_ruta_item'), ['estado_ruta_item'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_iniciador_ruta_id'), ['iniciador_ruta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_motivo_no_realizado'), ['motivo_no_realizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_orden_trabajo_id'), ['orden_trabajo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_ruta_grupo_id'), ['ruta_grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruta_item_ruta_trabajo_id'), ['ruta_trabajo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruta_item_ruta_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_ruta_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_orden_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_motivo_no_realizado'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_iniciador_ruta_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_estado_ruta_item'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_estado_ejecucion'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_ejecutado_por_user_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_item_actuacion_id'))

    op.drop_table('ruta_item')
    with op.batch_alter_table('inspeccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspeccion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_mes'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_anio'))
        batch_op.drop_index(batch_op.f('ix_inspeccion_actuacion_id'))

    op.drop_table('inspeccion')
    with op.batch_alter_table('iniciador_ruta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_turno_sugerido'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_tipo_iniciador'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_relevamiento_id'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_oficio_id'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_notificacion_id'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_mes'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_fecha_origen'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_estado_iniciador'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_denuncia_id'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_comprobacion_id'))
        batch_op.drop_index('ix_iniciador_ruta_anio_mes_turno_estado')
        batch_op.drop_index('ix_iniciador_ruta_anio_mes_tipo')
        batch_op.drop_index('ix_iniciador_ruta_anio_mes_estado')
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_anio'))
        batch_op.drop_index(batch_op.f('ix_iniciador_ruta_actuacion_id'))

    op.drop_table('iniciador_ruta')
    with op.batch_alter_table('decomiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decomiso_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_decomiso_mes'))
        batch_op.drop_index(batch_op.f('ix_decomiso_anio'))
        batch_op.drop_index(batch_op.f('ix_decomiso_actuacion_id'))

    op.drop_table('decomiso')
    with op.batch_alter_table('clausura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clausura_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_clausura_mes'))
        batch_op.drop_index(batch_op.f('ix_clausura_anio'))
        batch_op.drop_index(batch_op.f('ix_clausura_actuacion_id'))

    op.drop_table('clausura')
    op.drop_table('actuaciones_inspector')
    with op.batch_alter_table('actuacion_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actuacion_media_actuacion_id'))

    op.drop_table('actuacion_media')
    with op.batch_alter_table('actuacion_epicollect_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actuacion_epicollect_detalle_entry_uuid'))
        batch_op.drop_index(batch_op.f('ix_actuacion_epicollect_detalle_actuacion_id'))

    op.drop_table('actuacion_epicollect_detalle')
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actuaciones_tipo'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_orden_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_notificacion_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_nombre_local'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_mes'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_establecimiento_operativo_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_ec5_uuid'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_contraproducencia'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_actuaciones_anio'))
        batch_op.drop_index('idx_tipo_mes_anio')

    op.drop_table('actuaciones')
    with op.batch_alter_table('ruta_grupo_inspector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruta_grupo_inspector_ruta_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_grupo_inspector_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_grupo_inspector_created_by_user_id'))

    op.drop_table('ruta_grupo_inspector')
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relevamiento_turno_carga'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_mes'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_esta_abierto'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_anio'))

    op.drop_table('relevamiento')
    with op.batch_alter_table('establecimiento_operativo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_establecimiento_operativo_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_establecimiento_operativo_created_by_user_id'))

    op.drop_table('establecimiento_operativo')
    with op.batch_alter_table('domicilio_geocode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domicilio_geocode_geo_status'))
        batch_op.drop_index(batch_op.f('ix_domicilio_geocode_deleted_at'))

    op.drop_table('domicilio_geocode')
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_denuncia_mes'))
        batch_op.drop_index(batch_op.f('ix_denuncia_fecha'))
        batch_op.drop_index(batch_op.f('ix_denuncia_estado'))
        batch_op.drop_index(batch_op.f('ix_denuncia_domicilio_id'))
        batch_op.drop_index(batch_op.f('ix_denuncia_created_by_user_id'))
        batch_op.drop_index('ix_denuncia_anio_mes_estado')
        batch_op.drop_index('ix_denuncia_anio_mes_domicilio_id')
        batch_op.drop_index(batch_op.f('ix_denuncia_anio'))

    op.drop_table('denuncia')
    with op.batch_alter_table('ruta_grupo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruta_grupo_ruta_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_ruta_grupo_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_ruta_grupo_created_by_user_id'))

    op.drop_table('ruta_grupo')
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_tipo_expediente'))
        batch_op.drop_index(batch_op.f('ix_expediente_numero_expediente'))
        batch_op.drop_index(batch_op.f('ix_expediente_notificacion_id'))
        batch_op.drop_index(batch_op.f('ix_expediente_fecha_expediente'))
        batch_op.drop_index(batch_op.f('ix_expediente_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_expediente_anio'))

    op.drop_table('expediente')
    op.drop_table('evento_participante')
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domicilio_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_numero_tipo'))
        batch_op.drop_index(batch_op.f('ix_domicilio_numero'))
        batch_op.drop_index(batch_op.f('ix_domicilio_esquina_norm_status'))
        batch_op.drop_index(batch_op.f('ix_domicilio_esquina_catalogo_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_distrito_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_contribuyente_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle_norm_status'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle_key'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle_catalogo_id'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle'))
        batch_op.drop_index(batch_op.f('ix_domicilio_barrio_id'))

    op.drop_table('domicilio')
    with op.batch_alter_table('ruta_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruta_trabajo_turno'))
        batch_op.drop_index('ix_ruta_trabajo_fecha_turno_estado')
        batch_op.drop_index(batch_op.f('ix_ruta_trabajo_fecha'))
        batch_op.drop_index(batch_op.f('ix_ruta_trabajo_estado_ruta'))
        batch_op.drop_index(batch_op.f('ix_ruta_trabajo_created_by_user_id'))

    op.drop_table('ruta_trabajo')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_used_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_expires_at'))

    op.drop_table('password_reset_codes')
    with op.batch_alter_table('participantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participantes_lugar_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_participantes_dni'))

    op.drop_table('participantes')
    with op.batch_alter_table('oficio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oficio_numero_oficio'))
        batch_op.drop_index(batch_op.f('ix_oficio_juzgado_id'))
        batch_op.drop_index(batch_op.f('ix_oficio_fecha_oficio'))
        batch_op.drop_index(batch_op.f('ix_oficio_comprobacion_id'))
        batch_op.drop_index(batch_op.f('ix_oficio_causa'))
        batch_op.drop_index(batch_op.f('ix_oficio_anio'))

    op.drop_table('oficio')
    op.drop_table('notificacion_motivo')
    with op.batch_alter_table('inspector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspector_turno_id'))
        batch_op.drop_index(batch_op.f('ix_inspector_nombre'))
        batch_op.drop_index(batch_op.f('ix_inspector_legajo'))

    op.drop_table('inspector')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_fecha'))
        batch_op.drop_index(batch_op.f('ix_eventos_establecimiento_id'))

    op.drop_table('eventos')
    with op.batch_alter_table('barrio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barrio_nombre'))
        batch_op.drop_index(batch_op.f('ix_barrio_distrito_id'))
        batch_op.drop_index('idx_barrio_geom', postgresql_using='gist')

    op.drop_table('barrio')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turno_turno'))

    op.drop_table('turno')
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubro_nombre'))

    op.drop_table('rubro')
    with op.batch_alter_table('orden_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_mes'))
        batch_op.drop_index(batch_op.f('ix_orden_trabajo_anio'))

    op.drop_table('orden_trabajo')
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_notificacion_mes'))
        batch_op.drop_index(batch_op.f('ix_notificacion_fecha_vencimiento'))
        batch_op.drop_index(batch_op.f('ix_notificacion_fecha_notificacion'))
        batch_op.drop_index(batch_op.f('ix_notificacion_anio'))

    op.drop_table('notificacion')
    with op.batch_alter_table('motivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motivo_nombre'))

    op.drop_table('motivo')
    with op.batch_alter_table('lugares_trabajo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lugares_trabajo_nombre'))

    op.drop_table('lugares_trabajo')
    with op.batch_alter_table('juzgado_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_juzgado_catalogo_nombre'))
        batch_op.drop_index(batch_op.f('ix_juzgado_catalogo_codigo'))

    op.drop_table('juzgado_catalogo')
    with op.batch_alter_table('establecimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_establecimientos_nombre'))

    op.drop_table('establecimientos')
    with op.batch_alter_table('distrito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distrito_nombre'))
        batch_op.drop_index(batch_op.f('ix_distrito_codigo'))
        batch_op.drop_index('idx_distrito_geom', postgresql_using='gist')

    op.drop_table('distrito')
    with op.batch_alter_table('contribuyente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribuyente_razon_social'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_nombre'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_documento'))
        batch_op.drop_index(batch_op.f('ix_contribuyente_apellido'))

    op.drop_table('contribuyente')
    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobacion_numero_acta'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_motivo'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_mes'))
        batch_op.drop_index(batch_op.f('ix_comprobacion_anio'))

    op.drop_table('comprobacion')
    with op.batch_alter_table('catalog_tipo_actuacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_tipo_actuacion_nombre'))

    op.drop_table('catalog_tipo_actuacion')
    with op.batch_alter_table('catalog_motivo_comprobacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_motivo_comprobacion_nombre'))

    op.drop_table('catalog_motivo_comprobacion')
    with op.batch_alter_table('catalog_contraproducencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_contraproducencia_nombre'))

    op.drop_table('catalog_contraproducencia')
    with op.batch_alter_table('calle_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calle_catalogo_nombre_key'))
        batch_op.drop_index(batch_op.f('ix_calle_catalogo_canon_base'))

    op.drop_table('calle_catalogo')
    # ### end Alembic commands ###
