"""domicilio normalizacion calles

Revision ID: 9841d79dfa00
Revises: c0b8c8d2a359
Create Date: 2026-02-01 04:01:15.516410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9841d79dfa00'
down_revision = 'c0b8c8d2a359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: no se agrega SPATIAL INDEX para barrio/distrito en esta migración.
    op.create_table('calle_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_canonico', sa.String(length=255), nullable=False),
    sa.Column('nombre_key', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_canonico')
    )
    with op.batch_alter_table('calle_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calle_catalogo_nombre_key'), ['nombre_key'], unique=True)

    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calle_raw', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('calle_normalizada', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('calle_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('calle_catalogo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calle_norm_status', sa.String(length=32), nullable=False, server_default='PENDIENTE'))
        batch_op.add_column(sa.Column('calle_norm_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calle_norm_error', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('calle_norm_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_domicilio_calle_catalogo_id'), ['calle_catalogo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle_key'), ['calle_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_domicilio_calle_norm_status'), ['calle_norm_status'], unique=False)
        batch_op.create_foreign_key(None, 'calle_catalogo', ['calle_catalogo_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domicilio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_domicilio_calle_norm_status'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle_key'))
        batch_op.drop_index(batch_op.f('ix_domicilio_calle_catalogo_id'))
        batch_op.drop_column('calle_norm_updated_at')
        batch_op.drop_column('calle_norm_error')
        batch_op.drop_column('calle_norm_score')
        batch_op.drop_column('calle_norm_status')
        batch_op.drop_column('calle_catalogo_id')
        batch_op.drop_column('calle_key')
        batch_op.drop_column('calle_normalizada')
        batch_op.drop_column('calle_raw')

    with op.batch_alter_table('calle_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calle_catalogo_nombre_key'))

    op.drop_table('calle_catalogo')
    # ### end Alembic commands ###
