"""uq actuaciones noti/comprobacion por anio+tipo

Revision ID: ac902f362388
Revises: d61808daa772
Create Date: 2026-01-06 15:27:32.112045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac902f362388'
down_revision = 'd61808daa772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        ""

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('comprobacion', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
       
       

    # ### end Alembic commands ###
