"""relevamiento add inspector_id and contraproducencia

Revision ID: c0b8c8d2a359
Revises: 474ea4bf7edf
Create Date: 2026-01-28 19:51:24.947186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b8c8d2a359'
down_revision = '474ea4bf7edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraproducencia', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('inspector_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_relevamiento_contraproducencia'), ['contraproducencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_relevamiento_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_foreign_key(None, 'inspector', ['inspector_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relevamiento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_relevamiento_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_relevamiento_contraproducencia'))
        batch_op.drop_column('inspector_id')
        batch_op.drop_column('contraproducencia')

    # ### end Alembic commands ###
